// <auto-generated />
using System;
using FileMonitoring.DataAccess.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FileMonitoring.DataAccess.Migrations
{
    [DbContext(typeof(FileMonitoringContext))]
    [Migration("20191015145842_AddSendingFileTable")]
    partial class AddSendingFileTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("file_monitoring")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FileMonitoring.Common.Models.SendingFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("FileName");

                    b.Property<string>("Path");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Path", "FileName", "CreateDate");

                    b.ToTable("SendingFiles");
                });

            modelBuilder.Entity("FileMonitoring.Common.Models.SendingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.Property<DateTime?>("ProcessDate");

                    b.Property<string>("Recipient");

                    b.Property<int>("Status");

                    b.Property<Guid?>("Uid");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Path", "Name", "CreateDate");

                    b.ToTable("SendingTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
